---
title: "Empirical Smooth CDF"
output: html_notebook
---


```{r}

num_samples = 1000;
samples_source = rbinom(num_samples, 1, 0.5);
samples = samples_source * rnorm(num_samples, -2,0.2) + (1 - samples_source) * rnorm(num_samples, 2, 2)
true_density = function(x) { 0.5 * dnorm(x, -2, 0.2) + 0.5 * dnorm(x,2,2) }
true_cdf = function(x) { 0.5 * pnorm(x,-2,0.2) + 0.5 * pnorm(x,2,2) }
density_points = seq(-5,5, by = 0.01);
slope = 5
bandwidth = 1#1/slope
plot(density_points, true_cdf(density_points), type = "l", col="orange", main = "CDF", xlab = "", ylab = "CDF Value")
lines(density_points, ecdf(samples)(density_points), col="blue")
lines(density_points, empirical_smooth_cdf_logit(samples, slope, density_points), col = "magenta")
lines(density_points, empirical_smooth_cdf_normal(samples, bandwidth, density_points))

plot(density_points, true_density(density_points), type = "l", col = "orange", main = "Density", xlab = "", ylab = "Density")
lines(density_points, empirical_density_logit(samples, slope, density_points), col="magenta")
lines(density_points, empirical_density_normal(samples, bandwidth, density_points))

```

```{r}

kernel_estimate <- function(time, value_times, values, bandwidth) {
  result = array(0, length(time))
  for(i in 1:length(time)) {
    weights = exp(-0.5* (((value_times - time[i])  / bandwidth) ^ 2));
    result[i] = sum(weights * values) / sum(weights);
  }
  return(result)
}

time = 1:10
profile = generate_random_profile(time,3,1)
points = seq(1,10, by = 0.1)
linear = approx(time, profile, points)[["y"]]
kernel = kernel_estimate(points, time, profile, 0.5)
plot(time, profile)
lines(points, linear, col = "orange")
lines(points, kernel, col = "blue")
```

