---
title: "PCR Probablistic Model"
output: html_notebook
---


```{r setup}
library(ggplot2)
library(tidyverse)
library(magrittr)

density_pcr <- function(x, initial_no, prob_duplicate, n_cycles) {
  if(initial_no <= 0) {
    stop("Initial no. has to be positive")
  }
  if(any(x <= 0)) {
    stop("x has to be positive")
  }
  
  #computed_densities = array(-1, c(1:x,1:n_cycles))
  
  if(n_cycles == 0) {
    if(x == initial_no) {
      return(1);
    } else {
      return(0);
    }
  } else {
    if(x < initial_no) {
      return(0)
    } else if(x > initial_no * 2 ^ n_cycles) {
      return(0)
    }
    max_duplicated = floor(x / 2)
    prob = 0
    for(duplicated in 0:max_duplicated) {
      prob = prob + dbinom(duplicated, x - duplicated, prob_duplicate) * density_pcr(x - duplicated, initial_no, prob_duplicate, n_cycles - 1)
    }
    return(prob)
  }
}
```

```{r}
data = tibble(points = 1:64) %>%
  rowwise() %>%
  mutate(density = density_pcr(points, 1, 0.5, 7))

data %>%
  ggplot(aes(x = points, y = density)) + geom_col()
```

```{r}
pcr_state = tibble(init = c(1:10,seq(20, 100, by = 10), seq(200,1000, by = 100))) %>%
  mutate(amplified = init)

num_cycles = 10
amplify_prob = 0.5
num_samples = 100
result = NULL

for(s in 1:num_samples) {
  for(i in 1:num_cycles) {
    pcr_state %<>% mutate(amplified = amplified + rbinom(length(amplified), amplified, amplify_prob))
  }
  if(is.null(result)) {
    result = pcr_state
  } else {
    result = rbind(result, pcr_state)
  }
  pcr_state %<>% mutate(amplified = init)
}

result_copy = result %>% transmute(init2 = init, amplified2 = amplified)
result %>% expand(result, result_copy) %>% 
  mutate(initRatio = init/init2, amplifiedRatio = amplified / amplified2) %>%
  mutate(ratioRatio = initRatio / amplifiedRatio) %>%
  filter(ratioRatio < 5) %>%
  ggplot(aes(x =  ratioRatio)) + geom_histogram(binwidth = 0.1)  #geom_jitter()

```

